project_id = "gmdulobvxkgcfkfeydug"

[functions.meta-oauth]
verify_jwt = false

[functions.meta-fetch-insights]
verify_jwt = false

[functions.invite-admin]
verify_jwt = false

[functions.google-ads-oauth]
verify_jwt = false

[functions.google-ads-fetch-insights]
verify_jwt = false

[functions.google-ads-ai-gen]
verify_jwt = true

[functions.add-client-user]
verify_jwt = false

[functions.image-proxy]
verify_jwt = false
